name: Guim Perarnau
markdown: kramdown
permalink: /blog/:year/:month/:title
gems:
  - jekyll-sitemap
# Google services
google_analytics: UA-93553973-1
github_username:      Guim3
linkedin_username:    guimperarnau
